# Generated by Django 4.2.7 on 2023-12-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(max_length=100, null=True)),
                ('intensity', models.IntegerField(null=True)),
            ],
        ),
    ]
